# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Install
      run: | 
        cd tictactoe
        go mod download
        cd ..
        cd fourinarow
        go mod download
        cd ..
        cd intersection
        go mod download
        cd ..
        cd todo
        go mod download
        cd ..

    - name: Build
      run: | 
        cd tictactoe
        go build
        cd ..
        cd fourinarow
        go build
        cd ..
        cd intersection
        go build
        cd ..
        cd todo
        go build
        cd ..

    - name: Test
      run: | 
        cd tictactoe
        go test ./...
        cd ..
        cd fourinarow
        go test ./...
        cd ..
        cd intersection
        go test ./...
        cd ..
        cd todo
        go test ./...
        cd ..

    - name: Archive production artifacts - TicTacToe
      uses: actions/upload-artifact@v4
      with:
        name: tictactoe
        path:  tictactoe/tictactoe
    - name: Archive production artifacts - fourinarow
      uses: actions/upload-artifact@v4
      with:
        name: fourinarow
        path:  fourinarow/fourinarow
    - name: Archive production artifacts - Intersection
      uses: actions/upload-artifact@v4
      with:
        name: intersection
        path:  intersection/intersection
    - name: Archive production artifacts - ToDo
      uses: actions/upload-artifact@v4
      with:
        name: todo
        path:  todo/todo
